### ISSUE TITLE
lambda_model NaNs 

### ISSUE THREAD

**Issue by tomjf** [siriobelli/flame#1]
`	for i_OH=0, n_elements(speclines)-1 do lambda_model[i_OH] = $
		slit.outlambda_min + slit.outlambda_delta * total(((speclines[i_OH].y)^xexp # (speclines[i_OH].x)^yexp ) * Klambda)`

after this step lambda_model in wavecal_accurate is an array of NaNs. Cannot execute cgplot due to only having speclines.x but no y array

**Comment by tomjf** [comment]
lines 310-313 in flame_wavecal_accuate.pro

**Comment by tomjf** [comment]
flame has:

lammin        Infinity
dlamda   7.9432823e-05
speclines y      59.0000
xexp      0.00000      1.00000      2.00000      3.00000
speclines x       913.71314
yexp      0.00000      1.00000      2.00000      3.00000
klambda            -NaN            -NaN            -NaN            -NaN
            -NaN            -NaN            -NaN            -NaN
            -NaN            -NaN            -NaN            -NaN
            -NaN            -NaN            -NaN            -NaN

**Comment by tomjf** [comment]
polywarp gets NaNs for Klambda but values for Kgamma (line 81) @siriobelli

**Comment by siriobelli** [comment]
Clearly the problem is Klambda. How was the identification of sky lines (see *speclines.ps)? And what about the rough wavelength calibration?

**Comment by tomjf** [comment]
Not great, the rough wavelength calibration looks like it is a bit too far off from 0.58-0.75 microns.

Then I am guessing because the rough wavecal is too far out these lines aren't picked up at all on ID skylines (see pdf)? And then for some reason the accurate wavecal messes up on some rows returning a bad Klambda?

[wavelength_solution_estimate.pdf](https://github.com/siriobelli/flame/files/1031936/wavelength_solution_estimate.pdf)
[r161009_0035_corr_slit08_speclines.pdf](https://github.com/siriobelli/flame/files/1031938/r161009_0035_corr_slit08_speclines.pdf)

**Comment by siriobelli** [comment]
The rough wavelength solution is not perfect but it doesn't look too bad either. The problem is clearly that the row-by-row wavelength solution goes crazy. The interesting thing is that I get a good solution for this particular slit and frame. Perhaps you could try again with the latest version of flame?

Since the problem arises due to the small number of identified sky lines, a quick fix would be to set a higher value for fuel.util.identify_lines_Nmin_lines, which by default is six. If you set it to a higher number, that problematic row will be skipped altogether.
