### ISSUE TITLE
Option of combining arcs

### ISSUE THREAD

**Issue by cnaw** [siriobelli/flame#16]
While for most calibrations making a median combination is good, for arcs this is not  optimal
when the spectrograph has two or more arc lamps which are turned on sequentially,
For LUCI there are lamps of three different sources (Ne, Ar and Xe) and unless all lamps are shining simultaneously one ends getting more background than signal !  
In these cases a straight sum is probably the best option.

**Comment by siriobelli** [comment]
Very good point. I can add the option to sum instead of median combine, and then make sure that the arc lamp names are correctly read from all headers, as opposed to using just the first frame as currently done. Also, in the future it may be good to treat each arc lamp separately, so that the line identification is more robust, and then combine the wavelength solutions.

**Comment by siriobelli** [comment]
I think this would be too complicated to implement. I think the normal procedure should be to turn on all the lamps of interest simultaneously, I don't see any benefit in turning them on sequentially. Anyway, it should be easy enough to combine the arcs manually and edit the header to indicate the correct set of lamps, before running flame.
