### ISSUE TITLE
Identify skylines fails 

### ISSUE THREAD

**Issue by tomjf** [siriobelli/flame#4]
On a few problem slits identify skylines doesn't work. 

I am guessing this is because of the cut-off for including lines when compared to the fit. I.e. the initial rough fit isn't good enough so many of the lines are ignored.

[wavelength_solution_estimate_slit20.pdf](https://github.com/siriobelli/flame/files/1041533/wavelength_solution_estimate_slit20.pdf)

See the rough fit above and the identified lines for the previous OB before the code fails.

[r161009_0039_corr_slit20_speclines.pdf](https://github.com/siriobelli/flame/files/1041532/r161009_0039_corr_slit20_speclines.pdf)

**Comment by siriobelli** [comment]
The rough wavecal seems close enough for a reliable identification. In these cases it's normal that in the first few rows many sky lines are missed, but then with each successive fit the wavelength solution improves and after a few rows most lines should be identified. Here however row 21 is clearly off, with huge residuals. Maybe the problem is that curved wavelength solution in row 22? You could try using a lower identify_lines_poly_degree and see if it helps.

**Comment by tomjf** [comment]
Ok, that makes sense. I'll give that a go. 

Is there any way of changing a fuel parameter (that obviously hasn't been used yet) half way through the reduction or do you have to start from the beginning?

**Comment by siriobelli** [comment]
Absolutely, that's the whole point of the fuel structure. Just do fuel.util.identify_lines_poly_degree = 3 and then run again the identify_lines module.

**Comment by tomjf** [comment]
Ok! How easy!

I re-ran the from the beginning on just slit 20...

It worked fine with fuel.util.identify_lines_poly_degree = 4

[r161009_0039_corr_slit20_speclines.pdf](https://github.com/siriobelli/flame/files/1042075/r161009_0039_corr_slit20_speclines.pdf)

[r161009_0039_corr_slit20_plots.pdf](https://github.com/siriobelli/flame/files/1042078/r161009_0039_corr_slit20_plots.pdf)
